### ISSUE TITLE
ionic build error

### ISSUE THREAD

**Issue by wang3g** [daihere1993/corodva-plugin-gaode-location#1]
Hi,

I want to use Gaode map service in my Ionic 1.x project. So I installed cordova-plugin-gaode-location via command

cordova plugin add cordova-plugin-gaode-location --variable ANDROIDKEY=xxxxxxxxx --variable IOSKEY=xxxxxxxxx

Then, I ran 'ionic build android', but got the following error message:

================================
.........
:compileArmv7DebugJavaWithJavac

:compileArmv7DebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

/Users/qw/wg_app_cn/platforms/android/src/daihere/cordova/plugin/GaodeLocation.java:128: error: cannot find symbol

            AMapLocationClientOption.AMapLocationProtocol locationProtocol = para.isNull("enableHtpps") ? AMapLocationClientOption.AMapLocationProtocol.HTTP : AMapLocationClientOption.AMapLocationProtocol.HTTPS;

                                    ^

  symbol:   class AMapLocationProtocol

  location: class AMapLocationClientOption

/Users/qw/wg_app_cn/platforms/android/src/daihere/cordova/plugin/GaodeLocation.java:128: error: cannot find symbol

            AMapLocationClientOption.AMapLocationProtocol locationProtocol = para.isNull("enableHtpps") ? AMapLocationClientOption.AMapLocationProtocol.HTTP : AMapLocationClientOption.AMapLocationProtocol.HTTPS;

                                                                                                                                  ^

  symbol:   variable AMapLocationProtocol

  location: class AMapLocationClientOption

/Users/qiwang/wg_app_cn/platforms/android/src/daihere/cordova/plugin/GaodeLocation.java:128: error: cannot find symbol

            AMapLocationClientOption.AMapLocationProtocol locationProtocol = para.isNull("enableHtpps") ? AMapLocationClientOption.AMapLocationProtocol.HTTP : AMapLocationClientOption.AMapLocationProtocol.HTTPS;

                                                                                                                                                                                       ^

  symbol:   variable AMapLocationProtocol

  location: class AMapLocationClientOption

/Users/qw/wg_app_cn/platforms/android/src/daihere/cordova/plugin/GaodeLocation.java:131: error: cannot find symbol

            mOption.setWifiScan(para.isNull("enableWifiScan") ? true : para.getBoolean("enableWifiScan"));

                   ^

  symbol:   method setWifiScan(boolean)

  location: variable mOption of type AMapLocationClientOption

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: Some input files use unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.

4 errors

:compileArmv7DebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':compileArmv7DebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.872 secs

Error: /Users/qw/wg_app_cn/platforms/android/gradlew: Command failed with exit code 1 Error output:

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

/Users/qw/wg_app_cn/platforms/android/src/daihere/cordova/plugin/GaodeLocation.java:128: error: cannot find symbol

            AMapLocationClientOption.AMapLocationProtocol locationProtocol = para.isNull("enableHtpps") ? AMapLocationClientOption.AMapLocationProtocol.HTTP : AMapLocationClientOption.AMapLocationProtocol.HTTPS;

                                    ^

  symbol:   class AMapLocationProtocol

  location: class AMapLocationClientOption

/Users/qiwang/wg_app_cn/platforms/android/src/daihere/cordova/plugin/GaodeLocation.java:128: error: cannot find symbol

            AMapLocationClientOption.AMapLocationProtocol locationProtocol = para.isNull("enableHtpps") ? AMapLocationClientOption.AMapLocationProtocol.HTTP : AMapLocationClientOption.AMapLocationProtocol.HTTPS;

                                                                                                                                  ^

  symbol:   variable AMapLocationProtocol

  location: class AMapLocationClientOption

/Users/qw/wg_app_cn/platforms/android/src/daihere/cordova/plugin/GaodeLocation.java:128: error: cannot find symbol

            AMapLocationClientOption.AMapLocationProtocol locationProtocol = para.isNull("enableHtpps") ? AMapLocationClientOption.AMapLocationProtocol.HTTP : AMapLocationClientOption.AMapLocationProtocol.HTTPS;

                                                                                                                                                                                       ^

  symbol:   variable AMapLocationProtocol

  location: class AMapLocationClientOption

/Users/qiw/wg_app_cn/platforms/android/src/daihere/cordova/plugin/GaodeLocation.java:131: error: cannot find symbol

            mOption.setWifiScan(para.isNull("enableWifiScan") ? true : para.getBoolean("enableWifiScan"));

                   ^

  symbol:   method setWifiScan(boolean)

  location: variable mOption of type AMapLocationClientOption

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: Some input files use unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.

4 errors

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':compileArmv7DebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

=====

can you please kindly have a look at this issue?

Thanks a lot!

**Comment by daihere1993** [comment]
This is a confusing bug, I never met this error.Everything is fine when i `build android` in my project.
Please show your `ionic-cli` and `cordova` version.

**Comment by wang3g** [comment]
Thank you for your reply! Below is the version info:

ionic lib --> Local Ionic version: 1.3.2 
ionic -v  --> 1.2.4
cordova -v --> 7.0.1

**Comment by daihere1993** [comment]
1. Are you success when you remove the `cordova-plugin-gaode-location` plugin.
2. Try again after remove the plugin and android platform.

**Comment by wang3g** [comment]
yes,  the build will be succeed after the cordova-plugin-gaode-location plugin is removed.

**Comment by daihere1993** [comment]
That is so hard to know what's wrong of your project because of i can't reappear that error in my project. I suggest that you can debug the plugin by android studio.

**Comment by wang3g** [comment]
From the error message, "cannot find symbol: AMapLocationClientOption". It looks like "AMapLocationClientOption" got undefined. Do I need to install any other plugin before installing the cordova-plugin-gaode-location plugin?

**Comment by daihere1993** [comment]
What is the plugin version of you installed. 
AMap SDK already exist in the plugin. You can find that in `youProject/plugins/cordova-plugin-gaode-location/src/android/libs/Gaode_Location_SDK_V3.5.0.jar`.

**Comment by wang3g** [comment]
it shows 'plugin id="cordova-plugin-gaode-location" version="1.0.0"' in plugin.xml

**Comment by wang3g** [comment]
It shows "plugin id="cordova-plugin-gaode-location" version="1.0.0'"

**Comment by daihere1993** [comment]
Oh no~ 
So old version, now is ^1.8.6.
`ionic plugin rm cordova-plugin-gaode-location`
`ionic plugin add cordova-plugin-gaode-location`
Please reinstall and check the plugin version.

**Comment by wang3g** [comment]
The build is succeeded!

What happened is there is another plugin (cordova-amap-location) in my project which I think caused interference to your plugin. I just deleted it and the problem is gone!

Thank you very very much for your time!

**Comment by wang3g** [comment]
ok, let me try the latest version

**Comment by wang3g** [comment]
In plugin.xml, it show 1.0.0
<plugin id="cordova-plugin-gaode-location" version="1.0.0" xmlns="http://apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android">

But in package.json, it shows 1.8.6

        "raw": "cordova-plugin-gaode-location@1.8.6",
        "scope": null,
        "escapedName": "cordova-plugin-gaode-location",
        "name": "cordova-plugin-gaode-location",
        "rawSpec": "1.8.6",
        "spec": "1.8.6",
        "type": "version"

**Comment by daihere1993** [comment]
^1.0.0 is your project version.
^1.8.6 is `cordova-plugin-gaode-location` version.
Build fail again?

**Comment by wang3g** [comment]
no, build succeeded.
