### ISSUE TITLE
GaodeLocation.startUpdateLocation() is not a function

### ISSUE THREAD

**Issue by wang3g** [daihere1993/corodva-plugin-gaode-location#2]
Hi,

I put the following code into my ionic1 project. When it runs, a "GaodeLocation.startUpdateLocation() is not a function" error is shown in console. Can you pls help me on this issue?

// 定制参数
var para = {
  android: {
    // set some parameters
    gpsFirst: false,
    needAddress: true
  },
  ios: {
    // set some parameters
   needAddress: true
  }
}
// 啟動手機定位
GaodeLocation.startUpdateLocation(para, function (successMsg) {
  // do something
}, function (err) {
  console.log(err);
});

// 在啟動手機定位后即可通過'getLocation'隨時獲取最新的位置信息
GaodeLocation.getLocation(function (locationInfo) {
  // do something
}, function (err) {
  console.log(err);
});

**Comment by daihere1993** [comment]
What's your plugin version.

**Comment by daihere1993** [comment]
Only version 1.8.8 is work.

**Comment by daihere1993** [comment]
Last version is 1.8.8, only that version will be ok.

**Comment by wang3g** [comment]
I just upgraded to 1.8.8. The issue above is gone, but there are still some errors.

GaodeLocation.startUpdateLocation() returns the following error message:

定位失败
错误码12
错误信息缺少定位权限 请到http://lbs.amap.com/api/android-location-sdk/guide/utilities/errorcode/查看错误码说明,错误详细信息:定位权限被禁用,请授予应用定位权限#1201
错误描述定位权限被禁用,请授予应用定位权限#1201

**Comment by daihere1993** [comment]
You needs open app location setting in your device.
Some android device will occur this alert. I will change the alert way later.

**Comment by daihere1993** [comment]
I already finish this bug in last version.
